# Generated by Django 2.0.6 on 2018-07-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dianmai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security',
            old_name='name',
            new_name='securityName',
        ),
    ]
